### ISSUE TITLE
Question: How do I get Texture2D or Sprite from a Material container? 

### ISSUE THREAD

**Issue by FlandiaYingman** [K0lb3/UnityPy#103]
Hi, 

I was traversing containers by accessing `env.container`, I got a `Material` type object. When I opened the asset bundle file with AssetStudio, it showed that there were multiple `Texture2D` and `Sprite` assets inside the `Material` typed container. What should I do if I want to extract them out of the `Material` container? 

By the way, I've tried using the `env.objects` to traverse through all assets. However, by this method I was not able to get the container name of any asset (for example, `env.objects[0].container` returned `None`). That made me hard to determinate where to export the assets.

**Comment by K0lb3** [comment]
For the first issue, you can check
[MeshRendererExport#L48](https://github.com/K0lb3/UnityPy/blob/c00b8e78514a28d55aa36c39b56558252fbcf66d/UnityPy/export/MeshRendererExporter.py#L48) which does exactly that.

As you likely want to use it in combination with a ``Mesh``, do mind that meshes can use ``Mesh.m_Color`` to determine the vertex colors instead of a texture.



For the 2nd issue, the container usually only refers to "final" objects and not objects that are indirectly part of another object. E.g. materials are only "a part of" renderers, and are therefore not referred to by containers.

**Comment by FlandiaYingman** [comment]
> For the first issue, you can check [MeshRendererExport#L48](https://github.com/K0lb3/UnityPy/blob/c00b8e78514a28d55aa36c39b56558252fbcf66d/UnityPy/export/MeshRendererExporter.py#L48) which does exactly that.
> 
> As you likely want to use it in combination with a `Mesh`, do mind that meshes can use `Mesh.m_Color` to determine the vertex colors instead of a texture.
> 
> For the 2nd issue, the container usually only refers to "final" objects and not objects that are indirectly part of another object. E.g. materials are only "a part of" renderers, and are therefore not referred to by containers.

It does help me a lot. Thanks! 👍
