### ISSUE TITLE
Extracting fails when .resource is not in current directory

### ISSUE THREAD

**Issue by hydrargyrum** [K0lb3/UnityPy#19]
When extracting data from `foo/bar.asset`, it will fail to load resources from `foo/bar.resources` if we execute the script from another dir than `foo`, it seems `ResourceReader` only looks in current directory not in the directory from which the asset is (i.e. dir of `foo/bar.asset`).

**Comment by dblack2056** [comment]
I was actually messing with this in 15.something and I was running into a path issue (where path was blank sometimes). I had it output the path in order to sort this out and noticed that the directory it was looking in was something different than the directory the original file was in. I am not 100% sure why it was pointing there. I was able to point it at a different directory and it worked.... I have no idea where it got the other directory, so it isn't that it won't point at a different directory, it points at the wrong directory entirely. That being said, I would love to look into this issue further, but I need the weekend to come and want to resolve the aforementioned issue first.
![unknown](https://user-images.githubusercontent.com/71357479/105442632-4077b900-5c27-11eb-9ecf-09564114140c.png)

**Comment by K0lb3** [comment]
This issue should be fixed in the latest version, 1.6.0.1.
