### ISSUE TITLE
AttributeError: 'NodeHelper' object has no attribute 'name'

### ISSUE THREAD

**Issue by 28598519a** [K0lb3/UnityPy#197]
**Code**
![](https://github.com/K0lb3/UnityPy/assets/33422418/d0740af7-65a1-4a07-988c-a97285439dc0)

**Error**
![](https://github.com/K0lb3/UnityPy/assets/33422418/61667e1e-b9b0-4acb-9f5b-c5f2db46583b)

**To Reproduce**
- a copy of the file that causes the problem
- following data:
  - Python version 3.10.10
  - UnityPy version : 1.10.2

**Comment by 28598519a** [comment]
> Use
> 
> ```
> if hasattr(data, "name"):
>       obj_name = getattr(data, “name”)
> ```
> 
> Since not every stuff has name.

![image](https://github.com/K0lb3/UnityPy/assets/33422418/5cd32ab7-9a92-44a4-99fd-0a7fd7f575dd)

and got

![image](https://github.com/K0lb3/UnityPy/assets/33422418/b5d1b542-72a7-467d-835d-c7c08c142586)

but in the first comment you can see it should has name AssetBundleManifest. Directly print shows NodeHelper has the key "name" with -> "AssetBundleManifest"

I will give you the sample file, unzip and read the file inside.
[FileToRead.zip](https://github.com/K0lb3/UnityPy/files/13802298/FileToRead.zip)

**Comment by K0lb3** [comment]
``m_Name`` has to be used instead of ``name``.

AssetBundleManifest is not hardcorded and get instead parsed via its typetree,
which produces a class interface (NodeHelper) over a dict.

As the ``name`` and ``m_Name`` can be valid fields, I didn't add a wrapper for NodeHelper to prevent blocking access to a potential ``name`` field.
