### ISSUE TITLE
run a exe  miss uncompressed.tpk

### ISSUE THREAD

**Issue by EmilyEdna** [K0lb3/UnityPy#251]
Excuse me! when I use pyinstaller to package into EXE, and then I run the EXE program and get an error message, can you help me.

Error Info

`PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Jack\\AppData\\Local\\Temp\\_MEI54842\\UnityPy\\resources\\uncompressed.tpk'`

Here's my packing setup

`pyinstaller -D -p D:\Project\Unpack3d\Unpack3d\env\Lib\site-packages --add-binary="D:\Project\Unpack3d\Unpack3d\env\Lib\site-packages\UnityPy\resources\uncompressed.tpk;.\UnityPy\resources\uncompressed.tpk" -F D:\Project\Unpack3d\Unpack3d\Unpack3d.py`

**Comment by EmilyEdna** [comment]
![屏幕截图 2024-08-25 123230](https://github.com/user-attachments/assets/e70baa41-c61c-4685-9532-9616f8528f0a)

**Comment by K0lb3** [comment]
The problem is simply related to how UnityPy loads the tpk.
Currently it uses os.path, and I guess it's fair to assume that most tools don't check for things like this.

https://setuptools.pypa.io/en/latest/pkg_resources.html should likely work though.
I will fix this on Sunday.

**Comment by K0lb3** [comment]
Can you check if [this branch](https://github.com/K0lb3/UnityPy/pull/254) works for you?

**Comment by EmilyEdna** [comment]
I pulled the branch and tested my code on it, and I tried to package it with pyinstaller, but I still get an error
![屏幕截图 2024-09-02 114435](https://github.com/user-attachments/assets/79890cf4-0698-4912-8d02-82b9397c398f)

**Comment by mos9527** [comment]
According to [PyInstaller wiki](https://pyinstaller.org/en/stable/usage.html#cmdoption-add-data), with `--add-data` and `--add-binary` you should specify the **destination directory** instead of its **filename**.
> --add-data SOURCE:DEST[](https://pyinstaller.org/en/stable/usage.html#cmdoption-add-data)
Additional data files or directories containing data files to be added to the application. The argument value should be in form of **“source:dest_dir”, where source is the path to file (or directory) to be collected, dest_dir is the destination directory relative to the top-level application directory**, and both paths are separated by a colon (:). To put a file in the top-level application directory, use . as a dest_dir. This option can be used multiple times.

This should work as intended:
```powershell
pyinstaller -D -p D:\Project\Unpack3d\Unpack3d\env\Lib\site-packages --add-binary="D:\Project\Unpack3d\Unpack3d\env\Lib\site-packages\UnityPy\resources\uncompressed.tpk;.\UnityPy\resources" -F D:\Project\Unpack3d\Unpack3d\Unpack3d.py
```

FYI here are some other useful links related to using UnityPy with PyInstaller
- https://github.com/K0lb3/UnityPy/issues/184
- https://github.com/mos9527/sssekai/blob/main/sssekai.spec

**Comment by EmilyEdna** [comment]
> According to [PyInstaller wiki](https://pyinstaller.org/en/stable/usage.html#cmdoption-add-data), with `--add-data` and `--add-binary` you should specify the **destination directory** instead of its **filename**.
> 
> > --add-data SOURCE:DEST[](https://pyinstaller.org/en/stable/usage.html#cmdoption-add-data)
> > Additional data files or directories containing data files to be added to the application. The argument value should be in form of **“source:dest_dir”, where source is the path to file (or directory) to be collected, dest_dir is the destination directory relative to the top-level application directory**, and both paths are separated by a colon (:). To put a file in the top-level application directory, use . as a dest_dir. This option can be used multiple times.
> 
> This should work as intended:
> 
> ```powershell
> pyinstaller -D -p D:\Project\Unpack3d\Unpack3d\env\Lib\site-packages --add-binary="D:\Project\Unpack3d\Unpack3d\env\Lib\site-packages\UnityPy\resources\uncompressed.tpk;.\UnityPy\resources" -F D:\Project\Unpack3d\Unpack3d\Unpack3d.py
> ```
> 
> FYI here are some other useful links related to using UnityPy with PyInstaller
> 
> * [Using pyinstaller misses some files from UnityPy #184](https://github.com/K0lb3/UnityPy/issues/184)
> * https://github.com/mos9527/sssekai/blob/main/sssekai.spec

Thanks that fixed it for me,It's a great solution,i will close this this issuse
