### ISSUE TITLE
Lack of compression support in SerializedFile

### ISSUE THREAD

**Issue by JunkBeat** [K0lb3/UnityPy#282]
After saving an edited `SerializedFile`, I found that the file size increased significantly. I tried setting different values for the `packer` argument, but nothing seemed to work. Upon reviewing the source code, I noticed that compression is not actually implemented, which is frustrating because it results in `SerializedFile` sizes growing by an order of magnitude. 

Would it be possible for you to implement this feature, or could you please offer guidance on how to correctly compress a `SerializedFile`? That would be incredibly helpful. Thank you!

```python
with open(full_path, "wb") as f:
    f.write(file.save(packer="original"))
```
      
https://github.com/K0lb3/UnityPy/blob/6daa1f705543f998b434be5916447c480b3914e0/UnityPy/files/SerializedFile.py#L402

**Comment by K0lb3** [comment]
Web- and BundleFiles can contain compressed contents, with the contents being SerializedFiles and their connected resource files.
SerializedFiles themselves can't contain any compressed content.

If you patch a Texture2D, then UnityPy will store the related data in the SerializedFile, regardless if the Texture2D stored the data in itself or in a separate file. On top of that, if the Texture2D uses a TextureFormat for which no textures compression is implemented, then the given image for replacement won't be compressed and instead stored as raw rgba.

I assume that the last case might be your case.
There is no way around this issue, besides if you either set a compatible texture format (.set_image(image, texture format) instead of .image = ) or if you implement a compressor for the format used in the Texture2D.

**Comment by JunkBeat** [comment]
I don't really think it's the textures. There are very few of them in the file. To reproduce the actions: I extracted the contents of the assets file and packed it without changes (audio - converted to fsb5, textures - rgba). The size increased from 400 kb to 240 mb. This is strange considering that most of the packed files are dumps. 

I open both files in AssetStudioGui and see no errors in the console. 
Files: https://drive.google.com/file/d/1uhq7NDzUPUTVqA0NTIujK9479ZtZU8-0/view?usp=sharing
