### ISSUE TITLE
Open, how to save again, the resource size has increased a lot

### ISSUE THREAD

**Issue by 1xiaoming1314** [K0lb3/UnityPy#42]
I used a resource file to test. I just opened it and saved it again. The resource file changed from 30M to 300M. How to solve this? Below is the code I tested。

root = os.path.dirname(os.path.realpath(__file__))
fp = os.path.join(root,"data.unity3d")

env = UnityPy.load(fp)
with open("data_patch.unity3d", "wb") as f:
        f.write(env.file.save())

**Comment by K0lb3** [comment]
The Unity Engine itself uses lz4 compression for its bundles by default.
This is also possible with UnityPy, but since it can cause problems, it's not the default setting.

You can set the bundle compression by setting the packer kwarg in save.
[see](https://github.com/K0lb3/UnityPy/blob/390025aae56a4105f2001525d0ab0d1e0555eaab/UnityPy/files/BundleFile.py#L161)

As I said before, using compression can make the saved bundle unloadable by the game. I'm not yet exactly sure what causes the problem.


Another reason that can cause the size increase are edited textures. Unity itself usually uses some texture compression (dxt, etc, astc, ...) which usually reduces the texture size to 1/4 of the original size. The main problem with these compressions is, that they aren't lossless. So to keep the edited textures their original quality and to prevent problems, UnityPy doesn't use any compressions yet.

**Comment by 1xiaoming1314** [comment]
I'm glad to receive your reply. I'll compress it back in lz4 mode, which is similar to the original size. Repackage APK, the game will fail to load data. What is the possible reason for this？

**Comment by K0lb3** [comment]
Unity uses various undocumented flags for the data compression and usually splits the compressed data into multiple blocks.
UnityPy simply compressed the whole data into one big block and sets corresponding flags for it like UABE.

Sadly this doesn't always work and I can only guess that it has to do with either one of the issues or even both.
You can try using 'original', but besides that, I can't give any more advice.

**Comment by 1xiaoming1314** [comment]
Thank you for your answer. At present, the game I tested will be like this. Using "original" is the same as lz4, and the production size is also the same. I'll try other games to see if they are normal

**Comment by w0x12ef** [comment]
same issue ,the unity engine cannot be loaded

**Comment by w0x12ef** [comment]
Unable to read header from archive file: assets/bin/Data/data.unity3d
