### ISSUE TITLE
'EndianBinaryReader_Streamable' object has no attribute 'save'

### ISSUE THREAD

**Issue by Thuya1980** [K0lb3/UnityPy#51]
**Code**

        src = "D:\\ZTA\\MLBG Data\\#MLBGChanger-Python\\restore\\"+b
        src = b"bytes"
        src = io.BytesIO(b"Streamable")
        env = UnityPy.load(src)
        for obj in env.objects:
            if obj.type in ["Texture2D"]:
                # export texture
                data = obj.read()
                if data.name == a:
                    # edit texture
                    with Image.open(a+".png") as pil_img:
                        data.image = pil_img
                        data.save()
        with open(b, "wb") as f:
            f.write(env.file.save())

**Error**

        Traceback (most recent call last):
          File "D:\ZTA\MLBG Data\#MLBGChanger-Python\ImageConverter.py", line 78, in <module>
            f.write(env.file.save())
        AttributeError: 'EndianBinaryReader_Streamable' object has no attribute 'save'

**Bug**
I can't save it.

**Comment by K0lb3** [comment]
This code can't work and doesn't do what you're intended to do.

You pass 
src = io.BytesIO(b"Streamable")
to UnityPy.
The object isn't an Unity asset, so UnityPy will just store it as reader.

Since UnityPy got no Unity asset as input, it won't be able to find any objects,
so your loop below won't do anything, in fact, it will just be skipt as env.objects will be empty.
```python
    for obj in env.objects:
        if obj.type in ["Texture2D"]:
            # export texture
            data = obj.read()
            if data.name == a:
                # edit texture
                with Image.open(a+".png") as pil_img:
                    data.image = pil_img
                    data.save()
                    ```
 
 Since you don't change any asset, I'm wondering why you even try to repack/save the "asset".
 Anyway, since you're loading no Unity asset, the save command can't be applied to the only loaded file either.
