### ISSUE TITLE
Editing Texture2d is not working and It's just Black.

### ISSUE THREAD

**Issue by Thuya1980** [K0lb3/UnityPy#52]
**Bug**

When I edit the Texture2d obj from .unity3d file format with UnityPy, Image was changed but When i use it, the image is just Black and it's not working like an original one.
But When i edit with UABE, it's working well.
I found the diffrent between their changes!

The one  edited with UnityPy change the image in StreamingInfo m_StreamData But the one edited with UABE change in the TypelessData image data.
Is it relevant?

I provide the image for you.

UnityPy
![UnityPy](https://user-images.githubusercontent.com/67178590/120889371-bacb3780-c622-11eb-8f4d-bbeef75b62dd.JPG)

UABE
![UABE](https://user-images.githubusercontent.com/67178590/120889376-bf8feb80-c622-11eb-9f9f-a3d0c1021b28.JPG)

**Comment by w0x12ef** [comment]
@Thuya1980  have you solve this ?

**Comment by K0lb3** [comment]
Sorry, I was a bit busy irl.

I guess that the load failed because the resource file created by UnityPy isn't flagged as to be loaded intermediately.

I added a new function in 1.7.7 that can be used to decide yourself how the data of a Texture2D,
which currently always tries to store its data in a (newly created) cab, is stored.
The default arguments of [Texture2D.set_image](https://github.com/K0lb3/UnityPy/blob/e81952509f44f8cca1a03e84ec1d61b9b69a0699/UnityPy/classes/Texture2D.py#L47) store the image data within the Texture2D object lika UABE, so this might solve your problem.

**Comment by w0x12ef** [comment]
@K0lb3  where is 1.7.7

**Comment by UserUnknownFactor** [comment]
Something similar appeared for me too, with some game versions at least.

I did the following:

1st attempt:
1.  Imported image via the image setter with no cab so it embeded into **image_data** (the image size was set properly to the size of **image_data** aka width x height x bands).
2. The game crashes.

2nd attempt:
1.  Import image via UABE into **image_data** (the image is the same with the same **m_TextureFormat** as before but somehow it gets bigger than width x height x bands).
2. The game works.

3rd attempt:
1.  Import image via **m_StreamData** as an external file, the image is exactly the same(!) as in the first attempt (its size is width x height x bands; flipped raw bytes but as external file)
2. The game works.

I can't get my head around all of this.
